name: Deploy Doxygen

on:
  push:
    branches: [ current ]
  pull_request:
    branches: [ current ]

jobs:
  gen_doxygen:
    name: generate doxygen for gh-pages    
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: cd to repo
      run: echo $GITHUB_WORKSPACE && cd $GITHUB_WORKSPACE
    - name: install doxygen
      run: sudo apt-get install -y doxygen
    - name: run doxy      
      run: doxygen docs/config.in
    - name: Deploy 
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.AUTHVER }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/html # The folder the action should deploy. 
   
